### ISSUE TITLE
DBD

### ISSUE THREAD

**Issue by laurahermionetennant92** [DFE-Digital/manage-teacher-training-applications-prototype#9]
I've replaced this with 'Respond to the applicant by:' – we can come up with new content for the candidate facing comms.
But in this scenario when the offer has been made, can we add logic to make this message disappear? (trying to think if it's useful, will ask Kahar)
![Screenshot 2019-10-11 at 12 06 17](https://user-images.githubusercontent.com/38726669/66646969-8e79d080-ec1f-11e9-9cca-6432d706374b.png)

**Comment by paulrobertlloyd** [comment]
Ah, that text should appear if you’ve made an offer. Will fix.
